app/build.gradle, app/src/main/java/com/growthook/aos/App.kt, app/src/main/java/com/growthook/aos/di/RetrofitModule.kt, build.gradle
- closed #7 
퍼즐링으로 실험해봤는데 신기하네요
<br>
- kotlin 1.8.2 -> 1.8.1로 변경
- compose compiler 안정화 버전이 1.4.2 입니다. 근데 해당 커밋 내역 보면 가장 최근에 1.8.1 지원하는걸로 나와있어서 1.8.1로 수정했습니다.
- compose=true 안하면 materialDesign3 쓰기 힘들어서 추가해봤습니다.
- [참고 링크](https://developer.android.com/jetpack/androidx/releases/compose-compiler?hl=ko)
=> [CHORE] gradle 수정 & Flipper 추가

app/src/main/java/com/growthook/aos/domain/entity/Actionplan.kt, app/src/main/java/com/growthook/aos/presentation/insight/actionplan/AddActionplanActivity.kt, app/src/main/java/com/growthook/aos/presentation/insight/actionplan/AddActionplanAdapter.kt, app/src/main/java/com/growthook/aos/presentation/insight/actionplan/AddActionplanViewModel.kt, app/src/main/res/drawable/ic_collapse.xml, app/src/main/res/drawable/ic_more.xml, app/src/main/res/drawable/ic_plus.xml, app/src/main/res/drawable/rec_radius_bottom_10_gray600.xml, app/src/main/res/layout/activity_add_actionplan.xml, app/src/main/res/layout/item_actionplan_edittext.xml
- closed #17
https://github.com/Team-Growthook/Growthook-AOS/assets/62274335/787d391d-c67e-47c2-99c1-9fb2dd1cb7ca
- 완료 버튼 활성화 로직 구현은 기능 확정짓고 수정하겠습니다
=> [FEAT] 액션플랜 없는 인사이트 조회 UI 구현

app/src/main/java/com/growthook/aos/domain/entity/SeedInfo.kt, app/src/main/java/com/growthook/aos/presentation/insight/noactionplan/InsightMenuBottomsheet.kt, app/src/main/java/com/growthook/aos/presentation/insight/noactionplan/SeedModifyActivity.kt, app/src/main/java/com/growthook/aos/presentation/insight/noactionplan/SeedModifyViewModel.kt, app/src/main/java/com/growthook/aos/presentation/insight/noactionplan/model/SeedModifyIntent.kt, app/src/main/res/layout/activity_seed_modify.xml, app/src/main/res/values/strings.xml
- 수정 뷰
- 목표 기간 수정 시 토스트 띄우기
- 수정 완료 로직 
- closed #35 
https://github.com/Team-Growthook/Growthook-AOS/assets/128988935/e0201769-549b-4aae-884f-2c1e9690245a
=> [FEAT] 액션플랜 없는 인사이트 조회 뷰 - 수정

app/src/main/java/com/growthook/aos/presentation/cavedetail/CaveDetailActivity.kt, app/src/main/java/com/growthook/aos/presentation/home/HomeFragment.kt, app/src/main/java/com/growthook/aos/util/EmptyDataObserver.kt, app/src/main/java/com/growthook/aos/util/selectcave/NoApiCaveSelectBottomSheet.kt, app/src/main/java/com/growthook/aos/util/selectcave/YesApiCaveSelectBottomSheet.kt, app/src/main/res/drawable/ic_empty_cave.xml, app/src/main/res/layout/fragment_cave_select_bottomsheet.xml
- closed #32 
https://github.com/Team-Growthook/Growthook-AOS/assets/92314556/3fcc767e-0cd0-486a-a805-48c5921c2529
=> [ADD] empty 뷰 추가

app/src/main/java/com/growthook/aos/data/datasource/remote/CaveDataSource.kt, app/src/main/java/com/growthook/aos/data/datasource/remote/impl/CaveDataSourceImpl.kt, app/src/main/java/com/growthook/aos/data/model/request/RequestCavePostDto.kt, app/src/main/java/com/growthook/aos/data/model/response/ResponsePostCaveDto.kt, app/src/main/java/com/growthook/aos/data/repository/CaveRepositoryImpl.kt, app/src/main/java/com/growthook/aos/data/service/CaveService.kt, app/src/main/java/com/growthook/aos/domain/repository/CaveRepository.kt, app/src/main/java/com/growthook/aos/domain/usecase/PostCaveUseCase.kt, app/src/main/java/com/growthook/aos/domain/usecase/cavedetail/PostCaveUseCase.kt, app/src/main/java/com/growthook/aos/presentation/cavecreate/CreateNewCaveActivity.kt, app/src/main/java/com/growthook/aos/presentation/cavecreate/CreateNewCaveViewModel.kt, app/src/main/java/com/growthook/aos/presentation/cavecreate/SeeNewCaveActivity.kt, app/src/main/java/com/growthook/aos/presentation/cavecreate/SeeNewCaveViewModel.kt, app/src/main/res/layout/activity_create_new_cave.xml, app/src/main/res/layout/activity_see_new_cave.xml
- 보관함 생성 뷰 API 연결 
- closed #38
=> [FEAT] 보관함 생성 API 연결

app/src/main/java/com/growthook/aos/data/datasource/remote/SeedDataSource.kt, app/src/main/java/com/growthook/aos/data/datasource/remote/impl/SeedDataSourceImpl.kt, app/src/main/java/com/growthook/aos/data/model/request/RequestSeedModifyDto.kt, app/src/main/java/com/growthook/aos/data/repository/SeedRepositoryImpl.kt, app/src/main/java/com/growthook/aos/data/service/SeedService.kt, app/src/main/java/com/growthook/aos/domain/repository/SeedRepository.kt, app/src/main/java/com/growthook/aos/domain/usecase/seeddetail/ModifySeedUseCase.kt, app/src/main/java/com/growthook/aos/presentation/insight/noactionplan/InsightMenuBottomsheet.kt, app/src/main/java/com/growthook/aos/presentation/insight/noactionplan/NoActionplanInsightViewModel.kt, app/src/main/java/com/growthook/aos/presentation/insight/noactionplan/SeedModifyActivity.kt, app/src/main/java/com/growthook/aos/presentation/insight/noactionplan/SeedModifyViewModel.kt, app/src/main/res/layout/activity_seed_modify.xml
- 액션 플랜 없는 인사이트 조회 뷰-수정 서버 통신 
- closed #46
=> [FEAT] 인사이트 조회 (액션 플랜 X)  - 수정 서버 통신 

app/build.gradle, app/src/main/java/com/growthook/aos/data/datasource/remote/RefreshDataSource.kt, app/src/main/java/com/growthook/aos/data/datasource/remote/SignUpDataSource.kt, app/src/main/java/com/growthook/aos/data/datasource/remote/impl/RefreshDataSourceImpl.kt, app/src/main/java/com/growthook/aos/data/datasource/remote/impl/SignUpDataSourceImpl.kt, app/src/main/java/com/growthook/aos/data/model/request/RequestPostAuthDto.kt, app/src/main/java/com/growthook/aos/data/model/response/ResponsePostAuthDto.kt, app/src/main/java/com/growthook/aos/data/model/response/ResponseRefreshTokenDto.kt, app/src/main/java/com/growthook/aos/data/repository/RefreshRepository.kt, app/src/main/java/com/growthook/aos/data/repository/RefreshRepositoryImpl.kt, app/src/main/java/com/growthook/aos/data/repository/SignUpRepositoryImpl.kt, app/src/main/java/com/growthook/aos/data/repository/TokenRepositoryImpl.kt, app/src/main/java/com/growthook/aos/data/service/RefreshService.kt, app/src/main/java/com/growthook/aos/data/service/SignUpService.kt, app/src/main/java/com/growthook/aos/di/ApiModule.kt, app/src/main/java/com/growthook/aos/di/DataSourceModule.kt, app/src/main/java/com/growthook/aos/di/Qualifier.kt, app/src/main/java/com/growthook/aos/di/RefreshRetrofitModule.kt, app/src/main/java/com/growthook/aos/di/RepositoryModule.kt, app/src/main/java/com/growthook/aos/di/RetrofitModule.kt, app/src/main/java/com/growthook/aos/di/SignUpRetrofitModule.kt, app/src/main/java/com/growthook/aos/domain/repository/RefreshRepository.kt, app/src/main/java/com/growthook/aos/domain/repository/SignUpRepository.kt, app/src/main/java/com/growthook/aos/domain/repository/TokenRepository.kt, app/src/main/java/com/growthook/aos/domain/usecase/local/PostTokenUseCase.kt, app/src/main/java/com/growthook/aos/domain/usecase/onboarding/SignUpUseCase.kt, app/src/main/java/com/growthook/aos/presentation/onboarding/LoginActivity.kt, app/src/main/java/com/growthook/aos/presentation/onboarding/LoginViewModel.kt
- closed #59 
- 토큰 재발급은 지금 서버측에서 고치고 있어서 테스트는 못해봤습니다!
- 지금은 tokenInterceptor 안에 재발급 로직을 구현했는데, 추후에 Authenticator 를 이용해서 코드 정리하겠습니다! 자료가 적어서 생각보다 구현이 늦어질거 같아 미리 올립니다
=> [FEAT] 소셜로그인 api & 토큰 재발급 api 구현

app/src/main/java/com/growthook/aos/data/repository/SeedRepositoryImpl.kt, app/src/main/java/com/growthook/aos/domain/repository/SeedRepository.kt, app/src/main/java/com/growthook/aos/presentation/insight/write/InsightWriteActivity.kt, app/src/main/java/com/growthook/aos/presentation/insight/write/InsightWriteNewActivity.kt, app/src/main/java/com/growthook/aos/presentation/insight/write/InsightWriteNewViewModel.kt, app/src/main/java/com/growthook/aos/presentation/insight/write/InsightWriteViewModel.kt
- 씨앗 생성 후 씨앗 정보 뷰 그리기
- 액션플랜 뷰로 넘기기 
- closed #67
=> [FIX] 인사이트 작성 연결 안된 부분 구현 

app/src/main/java/com/growthook/aos/presentation/actionlist/completed/CompletedActionlistAdapter.kt, app/src/main/java/com/growthook/aos/presentation/actionlist/completed/CompletedActionlistFragment.kt, app/src/main/java/com/growthook/aos/presentation/actionlist/completed/CompletedActionlistViewModel.kt, app/src/main/java/com/growthook/aos/presentation/actionlist/proceeding/ProceedingActionlistAdapter.kt, app/src/main/java/com/growthook/aos/presentation/actionlist/proceeding/ProceedingActionlistFragment.kt, app/src/main/java/com/growthook/aos/presentation/actionlist/proceeding/ProceedingActionlistViewModel.kt, app/src/main/java/com/growthook/aos/presentation/home/HomeViewModel.kt, app/src/main/java/com/growthook/aos/presentation/insight/actionplan/ActionplanAdapter.kt, app/src/main/res/drawable/rect_gray600_fill_5.xml, app/src/main/res/layout/fragment_completed_actionlist.xml, app/src/main/res/layout/fragment_proceeding_actionlist.xml, app/src/main/res/layout/item_completed_actionplan.xml
=> [FEAT] 액션리스트 스크랩 기능 추가

app/src/main/java/com/growthook/aos/presentation/actionlist/proceeding/ProceedingActionlistFragment.kt, app/src/main/java/com/growthook/aos/presentation/cavecreate/CreateNewCaveActivity.kt, app/src/main/java/com/growthook/aos/presentation/cavedetail/CaveDetailActivity.kt, app/src/main/java/com/growthook/aos/presentation/cavedetail/CaveDetailSelectMenuBottomSheet.kt, app/src/main/java/com/growthook/aos/presentation/cavedetail/CaveDetailViewModel.kt, app/src/main/java/com/growthook/aos/presentation/home/HomeFragment.kt, app/src/main/java/com/growthook/aos/presentation/home/HomeViewModel.kt, app/src/main/java/com/growthook/aos/presentation/home/SelectMenuBottomSheet.kt, app/src/main/java/com/growthook/aos/presentation/insight/actionplan/ActionplanInsightActivity.kt, app/src/main/java/com/growthook/aos/presentation/insight/noactionplan/InsightMenuBottomsheet.kt, app/src/main/java/com/growthook/aos/presentation/insight/write/InsightWriteNewActivity.kt, app/src/main/java/com/growthook/aos/presentation/mypage/detailinfo/DetailMyPageActivity.kt, app/src/main/java/com/growthook/aos/util/base/BaseAlertDialog.kt, app/src/main/java/com/growthook/aos/util/dialog/LeftIntendedAlertDialog.kt, app/src/main/java/com/growthook/aos/util/dialog/RightIntendedAlertDialog.kt, app/src/main/java/com/growthook/aos/util/dialog/SingleIntendedAlertDialog.kt, app/src/main/res/layout/dialog_right_intended.xml
=> [FIX] Base dialog 수정

app/src/main/java/com/growthook/aos/presentation/actionlist/completed/CompletedActionlistFragment.kt, app/src/main/java/com/growthook/aos/presentation/actionlist/proceeding/ProceedingActionlistFragment.kt, app/src/main/java/com/growthook/aos/presentation/insight/actionplan/ActionplanAdapter.kt
=> [FIX] 인사이트 조회 -> 액션리스트 스크랩 반영

app/src/main/java/com/growthook/aos/presentation/actionlist/completed/CompletedActionlistAdapter.kt, app/src/main/java/com/growthook/aos/presentation/actionlist/completed/CompletedActionlistFragment.kt, app/src/main/java/com/growthook/aos/presentation/actionlist/proceeding/ProceedingActionlistAdapter.kt, app/src/main/java/com/growthook/aos/presentation/actionlist/proceeding/ProceedingActionlistFragment.kt, app/src/main/java/com/growthook/aos/presentation/cavecreate/CreateNewCaveActivity.kt, app/src/main/java/com/growthook/aos/presentation/cavecreate/SeeNewCaveActivity.kt, app/src/main/java/com/growthook/aos/presentation/cavedetail/CaveDetailActivity.kt, app/src/main/java/com/growthook/aos/presentation/cavedetail/CaveDetailSelectMenuBottomSheet.kt, app/src/main/java/com/growthook/aos/presentation/cavedetail/CaveModifySelectBottomSheet.kt, app/src/main/java/com/growthook/aos/presentation/cavedetail/cavemodify/CaveDetailModifyActivity.kt, app/src/main/java/com/growthook/aos/presentation/home/CaveAdapter.kt, app/src/main/java/com/growthook/aos/presentation/home/HomeFragment.kt, app/src/main/java/com/growthook/aos/presentation/home/HomeInsightAdapter.kt, app/src/main/java/com/growthook/aos/presentation/insight/actionplan/ActionplanAdapter.kt, app/src/main/java/com/growthook/aos/presentation/insight/actionplan/ActionplanInsightActivity.kt, app/src/main/java/com/growthook/aos/presentation/insight/noactionplan/InsightMenuBottomsheet.kt, app/src/main/java/com/growthook/aos/presentation/insight/noactionplan/NoActionplanInsightActivity.kt, app/src/main/java/com/growthook/aos/presentation/insight/noactionplan/SeedModifyActivity.kt, app/src/main/java/com/growthook/aos/presentation/insight/noactionplan/add/AddActionplanActivity.kt, app/src/main/java/com/growthook/aos/presentation/insight/write/InsightWriteActivity.kt, app/src/main/java/com/growthook/aos/presentation/insight/write/InsightWriteNewActivity.kt, app/src/main/java/com/growthook/aos/presentation/mypage/MyPageFragment.kt, app/src/main/java/com/growthook/aos/util/OnSingleClickListener.kt, app/src/main/java/com/growthook/aos/util/extension/ViewExt.kt
- closed #84 
- 일부러 스크랩 쪽이나, 중복 클릭이 크게 문제되지 않을거 같은 부분은 listener 적용 안했습니다.
=> [REFACTOR] setOnSingleClickListener

app/src/main/java/com/growthook/aos/util/selectcave/CaveSelect.kt, app/src/main/java/com/growthook/aos/util/selectcave/CaveSelectBottomSheetViewModel.kt, app/src/main/res/values/strings.xml
=> [FIX] 기획 수정에 따른 문구 수정

app/src/main/res/layout/activity_insight_write.xml, app/src/main/res/layout/activity_insight_write_new.xml, app/src/main/res/layout/activity_no_actionplan_insight.xml, app/src/main/res/layout/activity_see_new_cave.xml, app/src/main/res/layout/activity_seed_modify.xml
- 추가 QA 반영 
- closed #95 
caveId 수정은 서버 수정되면 이 pr에 같이 푸쉬하겠습니다
=> [QA] QA 반영 

app/src/main/java/com/growthook/aos/presentation/insight/actionplan/ActionplanInsightActivity.kt, app/src/main/java/com/growthook/aos/presentation/insight/noactionplan/NoActionplanInsightActivity.kt, app/src/main/java/com/growthook/aos/util/selectcave/CaveSelectBottomSheetViewModel.kt, app/src/main/res/layout/activity_actionplan_insight.xml, app/src/main/res/layout/activity_add_actionplan.xml, app/src/main/res/layout/activity_no_actionplan_insight.xml
=> [QA] 인사이트 margin 수정

app/src/main/java/com/growthook/aos/presentation/actionlist/proceeding/ProceedingActionlistFragment.kt, app/src/main/java/com/growthook/aos/presentation/insight/actionplan/ActionplanAdapter.kt, app/src/main/java/com/growthook/aos/presentation/insight/actionplan/ActionplanInsightActivity.kt, app/src/main/java/com/growthook/aos/presentation/insight/noactionplan/InsightMenuBottomsheet.kt, app/src/main/java/com/growthook/aos/util/base/BaseWritingBottomSheet.kt, app/src/main/java/com/growthook/aos/util/writingbottomsheet/LargeWritingBottomSheet.kt, app/src/main/java/com/growthook/aos/util/writingbottomsheet/SmallWritingBottomSheet.kt, app/src/main/res/layout/activity_actionplan_insight.xml, app/src/main/res/layout/activity_add_actionplan.xml, app/src/main/res/layout/activity_no_actionplan_insight.xml, app/src/main/res/layout/activity_review_detail.xml, app/src/main/res/layout/fragment_large_writing_bottomsheet.xml, app/src/main/res/layout/fragment_small_writing_bottomsheet.xml, app/src/main/res/layout/item_actionplan_edittext.xml, app/src/main/res/layout/item_completed_actionplan.xml, app/src/main/res/layout/item_proceeding_actionplan.xml, app/src/main/res/menu/main_menu.xml
=> [FEAT] UX 라이팅 수정

app/src/main/java/com/growthook/aos/presentation/insight/noactionplan/NoActionplanInsightActivity.kt
=> [FEAT] url 클립보드 복사 구현

app/src/main/java/com/growthook/aos/presentation/insight/noactionplan/NoActionplanInsightActivity.kt, app/src/main/java/com/growthook/aos/presentation/insight/write/InsightWriteActivity.kt, app/src/main/java/com/growthook/aos/presentation/insight/write/InsightWriteNewActivity.kt, app/src/main/java/com/growthook/aos/presentation/insight/write/InsightWriteViewModel.kt, app/src/main/res/drawable/rect_red200_line_05.xml, app/src/main/res/layout/activity_insight_write.xml, app/src/main/res/layout/activity_insight_write_new.xml, app/src/main/res/layout/activity_no_actionplan_insight.xml, app/src/main/res/values/strings.xml
- 출처 선택 사항으로 변경
- 출처 URL 유효성 검사
- closed #114
=> [FEAT] 인사이트 출처 관련 수정 

app/src/main/java/com/growthook/aos/presentation/cavecreate/SeeNewCaveActivity.kt, app/src/main/res/layout/activity_see_new_cave.xml
- 보관함 생성 이후 공개/비공개 팝업 노출
- closed #116
=> [FEAT] 보관함 생성 이후 공개/비공개 팝업 노출

app/src/main/java/com/growthook/aos/presentation/todolist/completed/CompletedActionlistFragment.kt
=> [FEAT] 삭제한 할일 뒤로가기시 반영

app/src/main/java/com/growthook/aos/presentation/todolist/proceeding/ProceedingActionlistFragment.kt, app/src/main/res/layout/item_completed_actionplan.xml, app/src/main/res/layout/item_proceeding_actionplan.xml
=> [FIX] 할일뷰 qa 반영

app/src/main/java/com/growthook/aos/presentation/insight/write/InsightWriteViewModel.kt
- 인사이트 출처 유효하지 않을 경우 등록 안되도록 수정
- closed #121
=> [FIX] 인사이트 출처 유효하지 않을 경우 등록 안되도록 수정

app/src/main/java/com/growthook/aos/presentation/todolist/completed/CompletedActionlistAdapter.kt
- 할일 아이템 리뷰 보기 활성화 여부에 따른 색상 수정
- closed #
=> [FIX] 할 일 완료 목록 btn 색상 수정
